<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>comment</key>
    <string>
    Homebrew (http://brew.sh) formulae support inlined diffs after an
    __END__ keyword. Now, this Syntax desccription you see here, named
    "Homebrew Formula.tmLanguage", merges `source.ruby` with `source.diff` and
    if you have a decent color theme, it will highlight changes in the diff
    and the __END__ as a keyword.

    Ruby (.rb) files beginning with `require 'formula'` are automatically
    detected.

    This tmLanguange here is simple enough, I wrote it directly in xml.

    Note:
    -   Updates to either source.ruby or source.diff are automatically
        used by this Syntax, too, because they are just included.
    -   I copy/pasted (start|stop)foldingStopMarker from
        Ruby.tmLanguage.

    Todo:
    -   Nothing. Do you have an idea? Let me know!

    Author:  Samuel John (www.SamuelJohn.de)
    License: Public Domain. I don't care. Have fun.
    </string>
    <key>fileTypes</key>
    <array>
        <string>rb</string>
    </array>
    <key>firstLineMatch</key>
    <string>^(#.*\n)*require ['"]formula['""].*$</string>
    <key>name</key>
    <string>Homebrew Formula (Ruby file with optional patch after __END__)</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>begin</key>
            <string>^(__END__)\n(.*\n)*</string>
            <key>name</key>
            <string>source.ruby.homebrew.patch</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>source.diff</string>
                </dict>
            </array>
            <key>end</key>
            <string>\n^$</string>
        </dict>
        <dict>
            <key>include</key>
            <string>source.ruby</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.ruby.homebrew</string>
    <key>uuid</key>
    <string>8EBEA374-AB74-0815-BEEF-1244461A3666</string>
</dict>
</plist>